### ISSUE TITLE
Issues after migration

### ISSUE THREAD

**Issue by joleaf** [joleaf/obsidian-better-pdf-2-plugin#1]
BY @jorosy
https://github.com/MSzturc/obsidian-better-pdf-plugin/issues/46#issuecomment-1593196679

> some issues I found. 
> 
> * The default Obsidian PDF View won't load any PDF while the plugin loaded.
> * Images inside PDF won't render in this plugin, it seems happen to all PDF. Feel free to download the[ sample PDF.](https://www.dropbox.com/s/sei1jscq269l58h/%E6%97%A5%E7%AB%8B%E6%B0%B8%E5%A4%A7%E9%9B%BB%E6%A2%AF_UAS6%E5%88%A5%E5%A2%85%E6%A2%AF%E5%9E%8B%E9%8C%84_Catalog-No.-YT-EL-0170-1.pdf?dl=0).
> 
> ![2023-06-15_22h26_25](https://github.com/MSzturc/obsidian-better-pdf-plugin/assets/5779706/6eda8732-eae9-4064-87f0-f320d88771b9)
>

**Comment by joleaf** [comment]
The second problem can be solved using an old version of pdfjs-dist -> `^2.16.105`.

However, I think I need help here to do this correctly because `pdf js` is used by obsidian as well, and there is somewhere a problem with the "worker":
The line
```
pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
```
is killing the obsidian pdf js worker which causes that the PDFs directly referenced by obsidian won't load.

**Comment by jorosy** [comment]
@joleaf 
Obsidian-slide-Note plugin is inspired by better pdf plugin and using pdfjs.
it works ok but without horizontal multi page tiling feature. 
Not sure if solution can be found in their source code.

Sorry, I don't have any coding knowledge to help out and just like to say thanks for trying to make it work for everyone.

**Comment by joleaf** [comment]
Hey @jorosy, thank you for this hint :)
Can you try version [2.0.3](https://github.com/joleaf/obsidian-better-pdf-2-plugin/releases/tag/2.0.3)?

**Comment by jorosy** [comment]
Hi, @joleaf . Everything works well. 
Thanks for your hard work and saved my life. :)
