### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by kaisandbrink** [joleaf/obsidian-better-pdf-2-plugin#3]
Hi! After downloading and unzipping to the Obsidian plugins folder, when I click "Refresh," the plugin shows up in my Obsidian plugins page, but when I try to turn it on, I get the message "the plugin failed to load." Is there something special that I need to do to get it to run? My apologies if this is a silly question!

**Comment by joleaf** [comment]
Mh, is the plugin named "Better PDF 2" or without the "2"?

**Comment by joleaf** [comment]
no reaction, closing this

**Comment by kaisandbrink** [comment]
My apologies about the late reply! I hereby confirm that the plugin is called "Better PDF 2" and that that is the name that pops up in the Obsidian Community Plugins page. In manifest.json, the ID is "better-pdf-2" version 2.0.3, and I have renamed the containing folder "obsidian-better-pdf-2".

**Comment by jonilaserson** [comment]
I can't seem to find it in the community plug-ins

**Comment by joleaf** [comment]
> I can't seem to find it in the community plug-ins

yes, this plugin will not be published, see https://github.com/obsidianmd/obsidian-releases/pull/2048
