### ISSUE TITLE
Plugin is dead in v1.4.16

### ISSUE THREAD

**Issue by fatkc** [joleaf/obsidian-better-pdf-2-plugin#5]
Obsidian is unable to load this plugin in most recent release!

**Comment by joleaf** [comment]
Not this version here.. Better PDF 2 is a fork of the original plugin.
See this [issue](https://github.com/MSzturc/obsidian-better-pdf-plugin/issues/46) for details ;)

**Comment by fatkc** [comment]
Thank you!x
